-- DB_CALENDAR START -- 
CREATE DATABASE DB_CALENDAR;
USE DB_CALENDAR;

-- USER_MEMBER
CREATE TABLE USER_MEMBER(
	NO	INT AUTO_INCREMENT,
    ID				VARCHAR(20)		NOT NULL,
    PW				VARCHAR(100)	NOT NULL,
    MAIL			VARCHAR(50)		NOT NULL,
    PHONE			VARCHAR(50)		NOT NULL,
    AUTHORITY_NO	TINYINT			DEFAULT 1,
    REG_DATE		DATETIME		DEFAULT NOW(),
    MOD_DATE		DATETIME		DEFAULT NOW(),
    PRIMARY KEY(NO)
);

-- USER_AUTHORITY
CREATE TABLE USER_AUTHORITY(
	NO	INT AUTO_INCREMENT,
    ROLE_NAME	VARCHAR(20) NOT NULL,
    PRIMARY KEY(NO)
);

INSERT INTO USER_AUTHORITY(ROLE_NAME) VALUES('PRE_USER');
INSERT INTO USER_AUTHORITY(ROLE_NAME) VALUES('USER');

-- DB_CALENDAR END -- 
SELECT * FROM USER_MEMBER;
SELECT * FROM USER_AUTHORITY;